// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBImDqltqlhjZ56ubxZq1hy6e1xm9Q-wn0',
    appId: '1:390695659143:web:012638264d07efee3cfa22',
    messagingSenderId: '390695659143',
    projectId: 'memosample-f9b97',
    authDomain: 'memosample-f9b97.firebaseapp.com',
    storageBucket: 'memosample-f9b97.appspot.com',
    measurementId: 'G-M3X9D8DEP6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIST7wu6paY-RjBDpl2Ck_wK93xoiKp94',
    appId: '1:390695659143:android:62c6ab0d9fa6453e3cfa22',
    messagingSenderId: '390695659143',
    projectId: 'memosample-f9b97',
    storageBucket: 'memosample-f9b97.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-s1_bME0FOLf0NdnW0Uc6tGPmskKgDAQ',
    appId: '1:390695659143:ios:7d064b6cfb65ea743cfa22',
    messagingSenderId: '390695659143',
    projectId: 'memosample-f9b97',
    storageBucket: 'memosample-f9b97.appspot.com',
    androidClientId: '390695659143-63ibab81j2rokejc9mpn4pkjpa6pvisg.apps.googleusercontent.com',
    iosClientId: '390695659143-ktv6q55llipea7f90ivan3s95l2n0hgf.apps.googleusercontent.com',
    iosBundleId: 'oke331.memoSample',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-s1_bME0FOLf0NdnW0Uc6tGPmskKgDAQ',
    appId: '1:390695659143:ios:7d064b6cfb65ea743cfa22',
    messagingSenderId: '390695659143',
    projectId: 'memosample-f9b97',
    storageBucket: 'memosample-f9b97.appspot.com',
    androidClientId: '390695659143-63ibab81j2rokejc9mpn4pkjpa6pvisg.apps.googleusercontent.com',
    iosClientId: '390695659143-ktv6q55llipea7f90ivan3s95l2n0hgf.apps.googleusercontent.com',
    iosBundleId: 'oke331.memoSample',
  );
}
